version: "3.7"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    entrypoint: docker/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - "${DB_PORT}:${DB_PORT}"

  celery:
    build: .
    command: celery worker --app=matchspecit --loglevel=info
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  celery-beat:
    build: .
    command: celery -A matchspecit beat -l info
    depends_on:
      - backend
      - redis

  redis:
    image: redis:5-alpine

volumes:
  postgres_data:
  django_static_volume:
