version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - django_static_volume:/app/static
    expose:
      - 8000
    env_file:
      - .env
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - "${DB_PORT}:${DB_PORT}"
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - django_static_volume:/app/django_files/static
    ports:
      - 80:80

volumes:
  postgres_data:
  django_static_volume:
