# Generated by Django 4.0 on 2022-07-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("technology", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("description", models.TextField(max_length=574, verbose_name="description")),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True)),
                ("is_matchable", models.BooleanField(blank=True, default=True, verbose_name="matchable")),
                ("is_finish", models.BooleanField(blank=True, default=False, verbose_name="finish")),
                ("is_successful", models.BooleanField(blank=True, default=False, verbose_name="successful")),
                ("is_deleted", models.BooleanField(blank=True, default=False, verbose_name="deleted")),
                ("image", models.ImageField(blank=True, null=True, upload_to="files/covers")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="użytkownik"
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(related_name="projects2technologies", to="technology.Technology"),
                ),
            ],
        ),
    ]
