# Generated by Django 4.0 on 2022-07-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
        ('user', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=574, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='finish'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_matchable',
            field=models.BooleanField(default=True, verbose_name='matchable'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_successful',
            field=models.BooleanField(default=False, verbose_name='successful'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='user.user',
                verbose_name='użytkownik'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects2technlogies', to='technology.Technology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
