# Generated by Django 4.0 on 2022-08-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="project_owner_approved",
            field=models.BooleanField(blank=True, null=True, default=None, verbose_name="akceptacja własciciela projektu"),
        ),
        migrations.AddField(
            model_name="match",
            name="specialist_approved",
            field=models.BooleanField(blank=True, null=True, default=None, verbose_name="akceptacja specjalisty IT"),
        ),
    ]
