name: MatchSpecIT CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: matchspecit.core.settings_test
      run: |
        python -m pip install --upgrade pip
        pip install pytest_django==4.5.2 pytest-xdist==2.4.0 pytest-sugar==0.9.4
        pytest --cov . -n 2
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8
    - name: Lint with isort
      run: |
        python -m pip install --upgrade pip
        pip install isort==5.10.1
        isort
    - name: Code quality with Black
      run: |
        python -m pip install --upgrade pip
        pip install black==22.3.0
        black . --check
